// <auto-generated />
namespace Mooshak_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removedpasswordfromuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedpasswordfromuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201605022059184_Removed password from user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
